# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [@mylocyrus, @mileycyrus]
patreon: # global.json channel angry channel mad channel money $ more confusion
bc1qahfakg7uk77xnan2ex8a55fd3ml30n65f7vw92
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['https://github.com/sponsors/HeartChain/sponsorships?sponsor=MyloCyrus&preview=false&frequency=recurring&amount=1000 play star of the Juju Beasts Cortana', '</river of blood>
</death channel self destruct>']
}
Hiragana Katakana
